---
title: "Assignment 1"
author: "Eryk Halicki (80922826)"
date: last-modified
format:
  html:
    embed-resources: true
    df-print: tibble
    html-math-method: mathml
execute:
  echo: true
---

```{r, echo=FALSE, warning=FALSE,message=FALSE}
library(tidyverse)
```

```{r}
obesity <- read.csv('/Users/erykhalicki/Documents/School/UBC/year3/DATA311/datasets/ObesityDataSet_raw_and_data_sinthetic.csv')

# Binary columns (yes/no)
obesity[c("family_history_with_overweight", "FAVC", "SMOKE", "SCC")] <- 
  lapply(obesity[c("family_history_with_overweight", "FAVC", "SMOKE", "SCC")], factor)

# Categorical columns
obesity[c("Gender", "CAEC", "CALC", "MTRANS")] <- 
  lapply(obesity[c("Gender", "CAEC", "CALC", "MTRANS")], factor)

# Integer columns
obesity[c("FCVC", "NCP", "TUE")] <- 
  lapply(obesity[c("FCVC", "NCP", "TUE")], as.integer)

obesity$NObeyesdad <- factor(obesity$NObeyesdad, 
    levels = c("Insufficient_Weight", "Normal_Weight", 
    "Overweight_Level_I", "Overweight_Level_II",
    "Obesity_Type_I", "Obesity_Type_II", 
    "Obesity_Type_III"),ordered = TRUE)

var_info <- data.frame(
  Variable = colnames(obesity),
  Type = sapply(obesity, function(x) class(x)[1]), # rename
  Description = c(
    "The gender of the participant",
    "Age of participant (years)",
    "Height (m)",
    "Weight (kg)",
    "Has a family member suffered or suffers from overweight?",
    "Do you eat high caloric food frequently?",
    "Do you usually eat vegetables in your meals?",
    "How many main meals do you have daily?",
    "Do you eat any food between meals?",
    "Do you smoke?",
    "How much water do you drink daily? (L)",
    "Do you monitor the calories you eat daily?",
    "How often do you have physical activity? (TODO FILL UNIT)",
    "How much time do you use technological devices such as cell phone, videogames, television, computer and others? (Hours per week)",
    "How often do you drink alcohol?",
    "Which transportation do you usually use?	",
    "Obesity level"
  )
)
```

This dataset contains data used to estimate the obesity levels in individuals from Mexico, Peru, and Columbia. The data is 77% synthetic and 23% was collected directly from users through a web platform. The dataset is sourced from https://archive.ics.uci.edu/dataset/544/estimation+of+obesity+levels+based+on+eating+habits+and+physical+condition, and has `{r} nrow(obesity)` rows and `{r} ncol(obesity)` variables: 
```{r} 
var_info
```





